apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2is
  namespace: argo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2is
  template:
    metadata:
      labels:
        app: wso2is
    spec:
      containers:
        - name: wso2is
          image: registry.fis-cp4d-dev.fis.com.vn:8443/wso2/wso2is:7.1.0.12
          ports:
            - containerPort: 9443
            - containerPort: 9763
---
apiVersion: v1
kind: Service
metadata:
  name: wso2is-service
  namespace: argo-test
spec:
  selector:
    app: wso2is
  ports:
    - name: https
      port: 9443
      targetPort: 9443
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wso2is
  namespace: argo-test
spec:
  to:
    kind: Service
    name: wso2is-service
  port:
    targetPort: https
  tls:
    termination: passthrough
