apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2is
  namespace: argo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: registry.fis-cp4d-dev.fis.com.vn:8443/wso2/wso2is:7.1.0.12
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wso2is-service
  namespace: argo-test
spec:
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wso2-route
  namespace: argo-test
spec:
  to:
    kind: Service
    name: hello
  port:
    targetPort: 80
